const G = {
    EVENT_USER_IN: 'EVENT_USER_IN',
    EVENT_USER_OUT: 'EVENT_USER_OUT',
    EVENT_USER_TOGGLE: 'EVENT_USER_TOGGLE',

    EVENT_USER_START: 'EVENT_USER_START',
    EVENT_USER_STOP: 'EVENT_USER_STOP',

    EVENT_NEW_SCRAMBLE: 'EVENT_NEW_SCRAMBLE',
    EVENT_ROUND_FINISHED: 'EVENT_ROUND_FINISHED',
    EVENT_ROUND_UNFINISHED: 'EVENT_ROUND_UNFINISHED'
};

export default G;